services:
  - type: web
    name: event-booking
    env: python
    runtime: docker
    plan: free
    region: oregon

    buildCommand: |
      python manage.py migrate
      pip install --upgrade pip
      pip install numpy==1.26.4
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: |
      python manage.py migrate
      

    postDeploy:
    - python manage.py migrate
    - python manage.py collectstatic --noinput

    autoDeploy: true

    envVars:
      - key: DJANGO_SECRET_KEY
        value: "k3bpdner)i2^!rwh43_ag^yw!&4*c+v8!4p)9^43ux2kfw3o$8"
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "event-booking-system-b8ak.onrender.com"

      # Database
      - key: DATABASE_URL
        value: "postgresql://eventbooking_db_user:UzqSIJQSaebqqHtU2bvwIjolsmJ0Wkg9@dpg-d194prruibrs73bqms50-a/eventbooking_db"

      # Gmail SMTP
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: "u2203052@rajagiri.edu.in"
      - key: EMAIL_HOST_PASSWORD
        value: "ygws ekzr zajb zbmt"
