# Generated by Django 5.2.1 on 2025-06-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="qr_codes/"),
        ),
    ]
