# Generated by Django 5.2.1 on 2025-06-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_event_image_event_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_checked_in",
            field=models.BooleanField(default=False),
        ),
    ]
